apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: second
  janus-idp.io/tekton: second
  backstage.io/kubernetes-id: second
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: second
resources: 
- deployment.yaml
- route.yaml
- service.yaml
