apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: second
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: second 
  name: second
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: second
    weight: 100 
